config/routes.rb
Rails.application.routes.draw do
  mount_roboto
  root to: 'welcome#index'
  resources :tags, only: :show do
    collection do
      get :search
    end
    member do
      get :ranking
    end
  end
  resources :users, only: :show
  resources :videos, only: :show
  # resources :videos
  #
  # get 'tag/:keyword', to: 'tags#search'
  # post 'tag/:keyword', to: 'tags#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'kawayuta' && password == 'nyaumyuuta1123'
  end
  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/user.rb
class User < ApplicationRecord

  require 'nokogiri'
  require 'open-uri'
  require 'socksify'

  has_many :videos

  def self.new_user(user_official_id)
    begin
      user_instance = User.find_by(user_official_id: user_official_id)
      unless user_instance.nil?
        user_data = User.get_user(user_official_id)
        return if user_data[:user_official_id].nil?

        ActiveRecord::Base.connection_pool.with_connection do
          puts "update user"
          user_instance.update(user_data)
        end
        unless UserHistory.where(user_official_id: user_official_id, created_at: Time.current.strftime("%Y-%m-%d").in_time_zone.all_day).present?
          ActiveRecord::Base.connection_pool.with_connection do
            puts "create history"
            UserHistory.create(user_data)
          end
        end
      else
        ActiveRecord::Base.connection_pool.with_connection do
          puts "new user & histories"
          user_data = User.get_user(user_official_id)
          return if user_data[:user_official_id].nil?

          user_instance = User.create(user_data)

          ActiveRecord::Base.connection_pool.with_connection do
            hash = User.group(:user_official_id).having('count(*) >= 2').maximum(:id)
            User.where(user_official_id: hash.keys).where.not(id: hash.values).destroy_all
          end
        end
      end

      return user_instance
    rescue => error
      UserUpdateWorker.perform_async(user_official_id)
    end
  end

  def self.get_user(user_official_id)
    begin
      Socksify::proxy("127.0.0.1", 9050) {
        url = URI.encode "https://m.tiktok.com/h5/share/usr/#{user_official_id}"
        charset = nil
        html = open(url) do |f|
          charset = f.charset
          f.read
        end
        doc = Nokogiri::HTML.parse(html, nil, charset)

        js = doc.css('script').to_s
        user_url = js.split('fullUrl":')[1].split(',')[0].delete('"').delete('}') unless js.split('fullUrl":')[1].nil?
        user_user_id = js.split('userId":')[1].split(',')[0].delete('"') unless js.split('userId":')[1].nil?
        user_user_sec_id = js.split('secUid":"')[1].split(',')[0].delete('"') unless js.split('secUid":"')[1].nil?
        user_user_unique_id = js.split('uniqueId":"')[1].split(',')[0].delete('"') unless js.split('uniqueId":')[1].nil?
        user_nick_name = js.split('nickName":')[1].split(',')[0].delete('"') unless js.split('nickName":')[1].nil?
        user_signature = js.split('signature":')[1].split(',')[0].delete('"') unless js.split('signature":')[1].nil?
        user_covers = js.split('covers":')[1].split(',')[0].delete('["').delete('"]') unless js.split('covers":')[1].nil?
        user_following_count = js.split('following":')[1].split(',')[0].delete('"') unless js.split('following":')[1].nil?
        user_fans_count = js.split('fans":')[1].split(',')[0].delete('"') unless js.split('fans":')[1].nil?
        user_heart_count = js.split('heart":')[1].split(',')[0].delete('"') unless js.split('heart":')[1].nil?
        user_verified = js.split('verified":')[1].split(',')[0].delete('"') unless js.split('verified":')[1].nil?

        user = {
            "user_official_id": user_user_id,
            "user_unique_id": user_user_unique_id,
            "user_sec_id": user_user_sec_id,
            "user_nick_name": user_nick_name,
            "user_signature": user_signature,
            "user_covers": user_covers,
            "user_following_count": user_following_count,
            "user_fans_count": user_fans_count,
            "user_heart_count": user_heart_count,
            "user_verified": user_verified,
            "user_url": "https://www.tiktok.com/@#{user_user_sec_id}"
        }
        return user
      }
    rescue => error
      puts "TASK_DATABASE 例外やで"
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @trending_videos = cache_videos_trending.take(10)
    @trending_tags = cache_tags_trending.take(10)

    @videos = @user.videos

    @videos_rank = @videos.sort_by {|array| Integer(array.video_interaction_count)}.first(10).reverse.to_a

    # @user_histries_posts_trans_following_count = cache_users_histories.select {|h|h.user_official_id == @user.user_official_id}.pluck(:created_at,:user_following_count).map { |e| [ e[0].strftime("%Y-%m-%d"), e[1] ] }
    @user_histries_posts_trans_fans_count = cache_users_histories.select {|h|h.user_official_id == @user.user_official_id}.pluck(:created_at,:user_fans_count).map { |e| [ e[0].strftime("%Y-%m-%d"), e[1] ] }
    @user_histries_posts_trans_heart_count = cache_users_histories.select {|h|h.user_official_id == @user.user_official_id}.pluck(:created_at,:user_heart_count).map { |e| [ e[0].strftime("%Y-%m-%d"), e[1] ] }

    @recommend_tags = @videos.pluck(:video_tags).flatten.compact.uniq.sort.reverse
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_official_id, :user_nick_name, :user_signature, :user_covers, :user_following_count, :user_fans_count, :user_heart_count, :user_video_count, :user_verified, :user_region, :user_url)
    end

    def cache_videos_trending
      Rails.cache.fetch("cache_videos_trending", expired_in: 60.minutes) do
        Video.eager_load(:user).where(video_trending: true).to_a
      end
    end

    def cache_tags_trending
      Rails.cache.fetch("cache_tags_trending", expired_in: 60.minutes) do
        Tag.where(tag_trending: true).to_a
      end
    end

    def cache_users_histories
      Rails.cache.fetch("cache_users_histories", expired_in: 60.minutes) do
        UserHistory.all.to_a
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_official_id %>
    <%= form.text_area :user_official_id %>
  </div>

  <div class="field">
    <%= form.label :user_nick_named %>
    <%= form.text_area :user_nick_named %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>User official</th>
      <th>User nick named</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_official_id %></td>
        <td><%= user.user_nick_named %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% set_meta_tags title: "🎉「#{@user.user_nick_name}」のプロフィール・おすすめ投稿動画", description: "#{@user.user_nick_name}のプロフィール、フォロー・フォロワー数や、おすすめ動画をご紹介。TikTok（ティックトック）アプリがパソコンでも観れるようになりました！TikTok Webでは人気クリエイターや動画のランキングから人気タグの情報をお届けします！現在、開発中です。" %>

<div class="contents_wrap">

  <section class="video_content">
    <div class="video_player">
      <div class="canvas_heart_bubble">
        <div class="swiper-container">
          <div class="swiper-wrapper">
            <div class="swiper-slide"><%= video_tag "", muted: true, controls: true, id:"video", class:"video_0", playsinline: true, autoplay: true %></div>
          </div>
          <div class="swiper-pagination"></div>
        </div>
      </div>
    </div>

    <% if @videos.present? %>
      <div class="video_content_meta">
        <h3 class="video_title"></h3>
        <div class="video_content_meta_tags">
          <p class="video_content_meta_tag"><a href=""></a></p>

        </div>
        <div class="video_content_meta_info">
          <p class="video_content_meta_info_play">
            <i class="material-icons">favorite</i> <span class="video_play_count"></span>
          </p>

          <p class="video_content_meta_info_comment">
            <i class="material-icons">comment</i> <span class="video_comment_count"></span>
          </p>
          <p class="video_content_meta_info_share">
            <i class="material-icons">share</i> <span class="video_share_count"></span>
          </p>
        </div>
      </div>

      <div class="video_content_profile">
        <div class="video_content_profile_image">
          <a class="video_user_covers" href=""><img src="" /></a>
        </div>
        <p class="video_user_nick_name"></p>
      </div>
    <% end %>

  </section>

  <article class="video_content_main">

    <section class="video_content_tag_info">
      <div class="video_content_tag_info_header">
        <figure class="profile_image">
          <%= image_tag @user.user_covers, alt: @user.user_nick_name unless @user.user_covers.nil? %>
        </figure>
        <h1><%= @user.user_nick_name unless @user.user_nick_name.nil? %></h1>
      </div>
      <div class="video_content_tag_info_meta">
        <p class="video_content_tag_info_meta_post">
          <%= @user.user_following_count unless @user.user_following_count.nil? %> <span>フォロー</span>
        </p>

        <p class="video_content_tag_info_meta_view">
          <%= @user.user_fans_count unless @user.user_fans_count.nil? %> <span>フォロワー(ファン)</span>
        </p>
        <p class="video_content_tag_info_meta_view">
          <%= @user.user_heart_count unless @user.user_heart_count.nil? %> <span>回いいね</span>
        </p>
      </div>
    </section>

    <section class="video_content_item">
      <h2><i class="material-icons">cake</i> <%= @user.user_nick_name %>のおすすめ動画</h2>
      <ul>
        <% if @videos.present? %>
          <% @videos.shuffle.each_with_index do |video, i| %>
            <li>
              <%= image_tag video.video_cover_image, class: "video_data video_index_#{i}", alt: video.video_title,
                            data: {video_source: video.video_url,
                                   video_index: i,
                                   video_title: video.video_title,
                                   video_tags: video.video_tags,
                                   video_play_count: video.video_interaction_count,
                                   video_comment_count: video.video_comment_count,
                                   video_share_count: video.video_share_count,
                                   video_user_covers: video.user.user_covers,
                                   video_user_nick_name: video.user.user_nick_name,
                                   video_user_id: video.user.id,
                            } %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </section>

    <div class="video_content_split_wrap">
      <div>
        <section class="video_content_item_ranking">
          <div class="video_content_item_ranking_header">
            <h2><i class="material-icons">cake</i> <%= @user.user_nick_name %>の人気動画ランキング</h2>
          </div>
          <ul>
            <% cache @videos_rank do %>
              <% @videos_rank.each_with_index do |video, index| %>
                <li>
                  <p class="rank_index rank_index_<%= index + 1 %>"><%= index + 1 %></p>
                  <div>
                    <%= link_to image_tag(video.video_cover_image, alt:video.video_title), video.user %>
                  </div>
                  <div>
                    <h3><%= video.video_title %></h3>
                    <div class="video_content_item_ranking_meta">
                      <p><i class="material-icons">favorite</i><%= video.video_interaction_count %></p>
                      <p><i class="material-icons">comment</i><%= video.video_share_count %></p>
                      <p><i class="material-icons">share</i><%= video.video_comment_count %></p>
                    </div>
                    <div class="video_content_item_ranking_user">
                      <%= link_to image_tag(video.user.user_covers, alt:video.user.user_nick_name), video.user %>
                      <p><%= video.user.user_nick_name %></p>
                    </div>
                  </div>
                </li>
              <% end %>
              <li class="ranking_more">
                <%#= link_to "もっと見る", ranking_tag_path(@tag) %>
              </li>
            <% end %>

          </ul>
        </section>
      </div>

      <div>
        <section class="video_content_item_transition">
          <h2><i class="material-icons">cake</i> <%= @user.user_nick_name %>のフォロワー(ファン)数 推移</h2>
          <% cache @user_histries_posts_trans_fans_count do %>
            <%= line_chart @user_histries_posts_trans_fans_count , xtitle: "日付", ytitle: "総再生回数" %>
          <% end %>
        </section>

        <section class="video_content_item_transition">
          <h2><i class="material-icons">cake</i> <%= @user.user_nick_name %>の総いいね数 推移</h2>
          <% cache @user_histries_posts_trans_heart_count do %>
            <%= line_chart @user_histries_posts_trans_heart_count , xtitle: "日付", ytitle: "動画投稿数" %>
          <% end %>
        </section>
      </div>
    </div>

    <section class="video_content_item_tags">
      <h2><i class="material-icons">cake</i> 関連するハッシュタグ</h2>
      <ul>
        <% if @videos.present? %>
          <% @recommend_tags.each do |tag| %>
            <li><%= link_to"##{tag}", search_tags_path(keyword: tag) %></li>
          <% end %>
        <% end %>
      </ul>
    </section>

  </article>

</div>

</body>
</html>