config/routes.rb
Rails.application.routes.draw do
  mount_roboto
  root to: 'welcome#index'
  resources :tags, only: :show do
    collection do
      get :search
    end
    member do
      get :ranking
    end
  end
  resources :users, only: :show
  resources :videos, only: :show
  # resources :videos
  #
  # get 'tag/:keyword', to: 'tags#search'
  # post 'tag/:keyword', to: 'tags#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'kawayuta' && password == 'nyaumyuuta1123'
  end
  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/video.rb
class Video < ApplicationRecord

  require 'nokogiri'
  require 'open-uri'
  require 'socksify'

  serialize :video_tags
  serialize :video_tags_official_ids

  belongs_to :user

  def self.new_video(video_official_id, user_instance)
    begin
      video_instance = Video.find_by(video_official_id: video_official_id)
      unless video_instance.nil?
        video_data = Video.get_video(video_official_id)
        return if video_data[:video_official_id].nil?

        ActiveRecord::Base.connection_pool.with_connection do
          puts "update video"
          video_instance.update(video_data)
        end
        unless VideoHistory.where(video_official_id: video_official_id, created_at: Time.current.strftime("%Y-%m-%d").in_time_zone.all_day).present?
          ActiveRecord::Base.connection_pool.with_connection do
            puts "create history"
            VideoHistory.create(video_data)
          end
        end
      else
        ActiveRecord::Base.connection_pool.with_connection do
          puts "new video & histories"
          video_data = Video.get_video(video_official_id)
          return if video_data[:video_official_id].nil?

          video_instance = user_instance.videos.create(video_data)

          ActiveRecord::Base.connection_pool.with_connection do
            hash = Video.group(:video_official_id).having('count(*) >= 2').maximum(:id)
            Video.where(video_official_id: hash.keys).where.not(id: hash.values).destroy_all
          end
        end
      end

      return video_instance
    rescue => error
      VideoUpdateWorker.perform_async(video_official_id, user_instance)
    end
  end

  def self.get_video(video_official_id)
    begin
      Socksify::proxy("127.0.0.1", 9050) {
        url = URI.encode "https://www.tiktok.com/embed/#{video_official_id}"
        charset = nil
        html = open(url) do |f|
          charset = f.charset
          f.read
        end
        doc = Nokogiri::HTML.parse(html, nil, charset)

        a = doc.css('script').to_s
        video_official_id = a.split('"id":"')[1].split('","')[0] unless a.split('"id":"')[1].nil?
        video_interaction_count = a.split('"diggCount":')[1].split(',"')[0] unless a.split('"diggCount":')[1].nil?
        video_share_count = a.split('"shareCount":')[1].split(',"')[0] unless a.split('"shareCount":')[1].nil?
        video_comment_count = a.split('"commentCount":')[1].split(',"')[0] unless a.split('"commentCount":')[1].nil?
        video_url = "https://tiktok.com/node/video/playwm?id=#{video_official_id}" unless video_official_id.nil?
        video_cover_url = a.split('"urlsOrigin":["')[1].split('"],"')[0] unless a.split('"urlsOrigin":["')[1].nil?

        video_text_title = a.split('"text":"')[1].split('","')[0].split('#')[0] unless a.split('"text":"')[1].nil?
        video_tags_title = a.split('"text":"')[1].split('","')[0].split('#').drop(1).map(&:strip!).compact! unless a.split('"text":"')[1].nil?

        video = {
            "video_url": video_url,
            "video_official_id": video_official_id,
            "video_title": video_text_title,
            "video_tags": video_tags_title,
            "video_comment_count": video_comment_count,
            "video_share_count": video_share_count,
            "video_interaction_count": video_interaction_count,
            "video_cover_image": video_cover_url,
            "video_trending": false
        }
        return video
      }
    rescue => error
      puts "TASK_DATABASE 例外やで"
    end

  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @trending_videos = cache_videos_trending.take(10)
    @trending_tags = cache_tags_trending.take(10)

    @videos = cache_videos_near

    @video_histries_posts_interaction_count = cache_videos_histories.select {|h|h.video_official_id == @video.video_official_id}.pluck(:created_at,:video_interction_count).map { |e| [ e[0].strftime("%Y-%m-%d"), e[1] ] }
    @video_histries_posts_share_count = cache_videos_histories.select {|h|h.video_official_id == @video.video_official_id}.pluck(:created_at,:video_share_count).map { |e| [ e[0].strftime("%Y-%m-%d"), e[1] ] }
    @video_histries_posts_comment_count = cache_videos_histories.select {|h|h.video_official_id == @video.video_official_id}.pluck(:created_at,:video_comment_count).map { |e| [ e[0].strftime("%Y-%m-%d"), e[1] ] }
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:user_official_id, :user_unique_id)
    end

  def cache_videos_near
    ids = (@video.id.to_i - 10)..(@video.id.to_i + 10)
    Video.eager_load(:user).where(id: ids.to_a).to_a
  end

  def cache_videos_trending
    Rails.cache.fetch("cache_videos_trending", expired_in: 60.minutes) do
      Video.eager_load(:user).where(video_trending: true).to_a
    end
  end

  def cache_tags_trending
    Rails.cache.fetch("cache_tags_trending", expired_in: 60.minutes) do
      Tag.where(tag_trending: true).to_a
    end
  end

  def cache_videos_histories
    VideoHistory.all.to_a
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= form_with(model: video, local: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_area :user_id %>
  </div>

  <div class="field">
    <%= form.label :user_unique_id %>
    <%= form.text_area :user_unique_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Videos</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>User unique</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.user_id %></td>
        <td><%= video.user_unique_id %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

app/views/videos/new.html.erb
<h1>New Video</h1>

<%= render 'form', video: @video %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<% set_meta_tags title: "🎉「#{@video.video_title}」 by #{@video.user.user_nick_name}", description: "#{@video.user.user_nick_name}さんの「#{@video.video_title}」をウェブで観よう！ いいね数「#{@video.video_interaction_count}」コメント数「#{@video.video_comment_count}」シェア数「#{@video.video_share_count}」- TikTok（ティックトック）アプリがパソコンでも観れるようになりました！TikTok Webでは人気クリエイターや動画のランキングから人気タグの情報をお届けします！現在、開発中です。" %>
<style> aside { display: none; }</style>

<article>
  <div class="swiper-container_single" data-video-id="<%= @video.id %>">
    <div class="swiper-wrapper">
      <div class="swiper-slide" style="height:600px;"><%= video_tag "", muted: true, controls: true, id:"video", class:"video_0", playsinline: true, autoplay: true %></div>
    </div>
    <div class="swiper-pagination"></div>
  </div>

  <% if @videos.present? %>
    <div class="video_single">
      <div class="video_content_meta">
        <h1 class="video_title"></h1>
        <div class="video_content_meta_tags">
          <p class="video_content_meta_tag"><a href=""></a></p>
        </div>
        <div class="video_content_meta_info">
          <p class="video_content_meta_info_play">
            <i class="material-icons">favorite</i> <span class="video_play_count"></span>
          </p>

          <p class="video_content_meta_info_comment">
            <i class="material-icons">comment</i> <span class="video_comment_count"></span>
          </p>
          <p class="video_content_meta_info_share">
            <i class="material-icons">share</i> <span class="video_share_count"></span>
          </p>
        </div>
      </div>

      <div class="video_content_profile">
        <div class="video_content_profile_image">
          <a class="video_user_covers" href=""><img src="" alt=""/></a>
        </div>
        <p class="video_user_nick_name"></p>
      </div>
    </div>

    <a class="tracker-link" href="">推移データを表示する。</a>

    <section class="video_content_item_transition">
      <h2><i class="material-icons">cake</i> いいね数 推移</h2>
      <%= line_chart @video_histries_posts_interaction_count , xtitle: "日付", ytitle: "いいね数" %>
    </section>

    <section class="video_content_item_transition">
      <h2><i class="material-icons">cake</i> シェア数 推移</h2>
      <%= line_chart @video_histries_posts_share_count , xtitle: "日付", ytitle: "シェア数" %>
    </section>

    <section class="video_content_item_transition">
      <h2><i class="material-icons">cake</i> コメント数 推移</h2>
      <%= line_chart @video_histries_posts_comment_count , xtitle: "日付", ytitle: "コメント数" %>
    </section>
  <% end %>

</article>

<div class="video_content_item" style="height:0px; overflow: hidden;">
  <ul>
    <% if @videos.present? %>
      <% @videos.each_with_index do |video, i| %>
        <li>
          <%= image_tag video.video_cover_image, class: "video_data video_index_#{i}", alt: video.video_title,
                        data: {video_source: video.video_url,
                               video_index: i,
                               video_id: video.id,
                               video_title: video.video_title,
                               video_tags: video.video_tags,
                               video_play_count: video.video_interaction_count,
                               video_comment_count: video.video_comment_count,
                               video_share_count: video.video_share_count,
                               video_user_covers: video.user.user_covers,
                               video_user_nick_name: video.user.user_nick_name,
                               video_user_id: video.user.id,
                        } %>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>