config/routes.rb
Rails.application.routes.draw do
  mount_roboto
  root to: 'welcome#index'
  resources :tags, only: :show do
    collection do
      get :search
    end
    member do
      get :ranking
    end
  end
  resources :users, only: :show
  resources :videos, only: :show
  # resources :videos
  #
  # get 'tag/:keyword', to: 'tags#search'
  # post 'tag/:keyword', to: 'tags#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #
  require 'sidekiq/web'
  require 'sidekiq-scheduler/web'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == 'kawayuta' && password == 'nyaumyuuta1123'
  end
  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/tag.rb
class Tag < ApplicationRecord

  require 'nokogiri'
  require 'open-uri'
  require 'socksify'

  def self.new_tag(search)
    begin
      tag_instance = Tag.find_by(tag_title: search)
      unless tag_instance.nil?
        tag_data = Tag.get_tag("https://www.tiktok.com/tag/#{search}")
        return if tag_data[:tag_official_id].nil?

        ActiveRecord::Base.connection_pool.with_connection do
            puts "update tag"
            tag_instance.update(tag_data)
        end
        unless TagHistory.where(tag_title: search, created_at: Time.current.strftime("%Y-%m-%d").in_time_zone.all_day).present?
          ActiveRecord::Base.connection_pool.with_connection do
            puts "create history"
            TagHistory.create(tag_data)
          end
        end
      else
        ActiveRecord::Base.connection_pool.with_connection do
          puts "new tag & histories"
          tag_data = Tag.get_tag("https://www.tiktok.com/tag/#{search}")
          return if tag_data[:tag_official_id].nil?

          tag_instance = Tag.create(tag_data)
          tag_instance.updated_at = "2000-01-01"
          tag_instance.save

          ActiveRecord::Base.connection_pool.with_connection do
            hash = Tag.group(:tag_official_id).having('count(*) >= 2').maximum(:id)
            Tag.where(tag_official_id: hash.keys).where.not(id: hash.values).destroy_all
          end
        end
      end

      return tag_instance

    rescue => error
      TagUpdateWorker.perform_async(search)
    end
  end
  def self.get_tag(url)
    Socksify::proxy("127.0.0.1", 9050) {
      url = URI.encode url
      charset = nil

      html = open(url) do |f|
        charset = f.charset
        f.read
      end

      doc = Nokogiri::HTML.parse(html, nil, charset)

      js = doc.search('script').to_s
      tag_official_id = js.split('challengeId":')[1].split(',')[0].delete('"') unless js.split('challengeId":')[1].nil?
      tag_title = js.split('challengeName":')[1].split(',')[0].delete('"') unless js.split('challengeName":')[1].nil?
      tag_text = js.split('","text":"')[1].split(',')[0].delete('"') unless js.split('","text":"')[1].nil?
      tag_cover_image = js.split('covers":')[1].split(',')[0].delete('["').delete('"]') unless js.split('covers":')[1].nil?
      tag_posts_count = js.split('posts":')[2].split(',')[0] unless js.split('posts":')[2].nil?
      tag_views_count = js.split('views":')[2].split(',')[0].delete('"').delete('}') unless js.split('views":')[2].nil?
      tag_url = url

      tag = {
          "tag_official_id": tag_official_id,
          "tag_title": tag_title,
          "tag_text": tag_text,
          "tag_cover_image": tag_cover_image,
          "tag_posts_count": tag_posts_count,
          "tag_views_count": tag_views_count,
          "tag_url": tag_url
      }
      return tag
    }
  end

  def self.get_data_from_keyword(search)
    begin
      Socksify::proxy("127.0.0.1", 9050) {
        url = URI.encode "https://www.tiktok.com/tag/#{search}"
        charset = nil
        html = open(url) do |f|
          charset = f.charset
          f.read
        end
        doc = Nokogiri::HTML.parse(html, nil, charset)
        embeds = []
        script = doc.css('script').to_s
        script.split('"embedUrl":"').drop(1).each do |n|
          embeds.push(n.split('","')[0])
        end

        embeds.uniq.each do |url|
          DataFromEmbedWorker.perform_async(url, false)
        end

      }
    rescue => error
    end

  end

  def self.get_data_from_embed(url, is_trending)
    begin
      Socksify::proxy("127.0.0.1", 9050) {
        url = URI.encode url
        charset = nil
        html = open(url) do |f|
          charset = f.charset
          f.read
        end
        doc = Nokogiri::HTML.parse(html, nil, charset)
        a = doc.css('script').to_s
        video_official_id = a.split('"id":"')[1].split('","')[0] unless a.split('"id":"')[1].nil?
        video_tags_title = a.split('"text":"')[1].split('","')[0].split('#').drop(1).map(&:strip!).compact! unless a.split('"text":"')[1].nil?
        user_official_id = a.split('"userId":"')[1].split('","')[0] unless a.split('"userId":"')[1].nil?

        user_instance = User.new_user(user_official_id)
        video_instance = Video.new_video(video_official_id, user_instance)
        video_instance.video_trending = is_trending
        video_instance.save!

        unless video_tags_title.nil?
          video_tags_title.each do |tag|
            tag_instance = Tag.new_tag(tag)
            tag_instance.tag_trending = is_trending
            tag_instance.save!
          end
        end
      }
    rescue => error
      DataFromEmbedWorker.perform_async(url, is_trending)
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :ranking]
  before_action :search_params, only: [:search]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show

    return redirect_to root_path if @tag.nil?

    @trending_videos = cache_videos_trending.take(10)
    @trending_tags = cache_tags_trending.take(10)

    @videos_data = cache_videos
    @videos = @videos_data.select { |v| v.video_tags.include?(@tag.tag_title.downcase) || v.video_tags.include?(@tag.tag_title.upcase) unless v.video_tags.nil? }
    @videos_rank = @videos.sort_by {|array| Integer(array.video_interaction_count) unless array.video_interaction_count.nil?}.reverse.first(10)

    @tag_histries_posts_trans_views_count = cache_tags_histories.select {|h|h.tag_title == @tag.tag_title}.pluck(:created_at,:tag_views_count).map { |e| [ e[0].strftime("%Y-%m-%d"), e[1] ] }
    @tag_histries_posts_trans_posts_count = cache_tags_histories.select {|h|h.tag_title == @tag.tag_title}.pluck(:created_at,:tag_posts_count).map { |e| [ e[0].strftime("%Y-%m-%d"), e[1] ] }

    @recommend_tags = @videos.pluck(:video_tags).flatten.compact.uniq.sort.reverse
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search

    keyword = search_params[:keyword].gsub(" ", "")

    return redirect_to root_path if keyword == ""

    @tag = Tag.find_by(tag_title: keyword)

    if @tag.nil?
      @tag = Tag.create(tag_title: keyword)
      @tag.updated_at = "2000-01-01"
      @tag.tag_url = "https://www.tiktok.com/tag/#{keyword}"
      @tag.tag_trending = false
      @tag.save
    end

    if @tag.updated_at.strftime("%Y-%m-%d") != Time.current.strftime("%Y-%m-%d")
      Tag.get_data_from_keyword(keyword)
    end

    redirect_to tag_path(@tag.id)

  end

  def ranking
    @trending_videos = cache_videos_trending.take(10)
    @trending_tags = cache_tags_trending.take(10)

    @videos_data = cache_videos
    @videos = @videos_data.select { |v| v.video_tags.include?(@tag.tag_title) unless v.video_tags.nil? }

    @videos_interaction_rank = @videos.sort_by {|array| Integer(array.video_interaction_count) unless array.video_interaction_count.nil?}.reverse.first(50)
    @videos_comment_rank = @videos.sort_by {|array| Integer(array.video_comment_count) unless array.video_comment_count.nil?}.reverse.first(50)
    @videos_share_rank = @videos.sort_by {|array| Integer(array.video_share_count) unless array.video_share_count.nil?}.reverse.first(50)

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find_by(id: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:user_official_id, :user_nick_named)
    end

    def search_params
      params.permit(:keyword)
    end

    def cache_videos
      Video.eager_load(:user).all.to_a
      # Rails.cache.fetch("cache_videos", expired_in: 60.minutes) do
      #
      # end
    end

    def cache_videos_trending
      Rails.cache.fetch("cache_videos_trending", expired_in: 60.minutes) do
        Video.eager_load(:user).where(video_trending: true).to_a
      end
    end

    def cache_tags_trending
      Rails.cache.fetch("cache_tags_trending", expired_in: 60.minutes) do
        Tag.where(tag_trending: true).to_a
      end
    end

    def cache_tags_histories
      TagHistory.all.to_a
    end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with(model: tag, local: true) do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_official_id %>
    <%= form.text_area :user_official_id %>
  </div>

  <div class="field">
    <%= form.label :user_nick_named %>
    <%= form.text_area :user_nick_named %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tags</h1>

<table>
  <thead>
    <tr>
      <th>User official</th>
      <th>User nick named</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.user_official_id %></td>
        <td><%= tag.user_nick_named %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', tags_path %>

app/views/tags/ranking.html.erb
<% set_meta_tags title: "🎉「##{@tag.tag_title}」タグの「いいね！・コメント数・シェア数」動画ランキング", description: "「##{@tag.tag_title}」タグの「いいね！・コメント数・シェア数」動画ランキング - TikTok（ティックトック）アプリがパソコンでも観れるようになりました！TikTok Webでは人気クリエイターや動画のランキングから人気タグの情報をお届けします！現在、開発中です。" %>

<article class="tag_ranking_info">
  <section class="video_content_tag_info">
    <div class="video_content_tag_info_header">

      <%= image_tag('hash_tag.png', alt:"#") %>

      <h1>「#<%= @tag.tag_title %>」タグの「いいね！・コメント数・シェア数」動画ランキング</h1>
    </div>
    <div class="video_content_tag_info_meta">
      <p class="video_content_tag_info_meta_post">
        <%= @tag.tag_posts_count unless @tag.tag_posts_count.nil? %> <span>投稿</span>
      </p>

      <p class="video_content_tag_info_meta_view">
        <%= @tag.tag_views_count unless @tag.tag_views_count.nil? %> <span>回再生</span>
      </p>
    </div>
  </section>

  <div class="split_wrap">
    <section class="video_content_item_ranking">
      <h2><i class="material-icons">cake</i> 「いいね！数」ランキング</h2>
      <ul>
        <% @videos_interaction_rank.each_with_index do |video, index| %>
          <li>
            <p class="rank_index rank_index_<%= index + 1 %>"><%= index + 1 %></p>
            <div>
              <%= link_to image_tag(video.video_cover_image, alt:video.video_title), video.user %>
            </div>
            <div>
              <h3><%= video.video_title %></h3>
              <div class="video_content_item_ranking_meta">
                <i class="material-icons">favorite</i> <%= video.video_interaction_count %></p>
                <p><i class="material-icons">comment</i> <%= video.video_comment_count %></p>
                <p><i class="material-icons">share</i> <%= video.video_share_count %></p>
              </div>
              <div class="video_content_item_ranking_user">
                <%= link_to image_tag(video.user.user_covers, alt:video.user.user_nick_name), video.user %>
                <p><%= video.user.user_nick_name %></p>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </section>

    <section class="video_content_item_ranking">
      <h2><i class="material-icons">cake</i> 「コメント数」ランキング</h2>
      <ul>
        <% @videos_comment_rank.each_with_index do |video, index| %>
          <li>
            <p class="rank_index rank_index_<%= index + 1 %>"><%= index + 1 %></p>
            <div>
              <%= link_to image_tag(video.video_cover_image, alt:video.video_title), video.user %>
            </div>
            <div>
              <h3><%= video.video_title %></h3>
              <div class="video_content_item_ranking_meta">
                <i class="material-icons">favorite</i> <%= video.video_interaction_count %></p>
                <p><i class="material-icons">comment</i> <%= video.video_comment_count %></p>
                <p><i class="material-icons">share</i> <%= video.video_share_count %></p>
              </div>
              <div class="video_content_item_ranking_user">
                <%= link_to image_tag(video.user.user_covers, alt:video.user.user_nick_name), video.user %>
                <p><%= video.user.user_nick_name %></p>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </section>

    <section class="video_content_item_ranking">
      <h2><i class="material-icons">cake</i> 「シェア数」ランキング</h2>
      <ul>
        <% @videos_share_rank.each_with_index do |video, index| %>
          <li>
            <p class="rank_index rank_index_<%= index + 1 %>"><%= index + 1 %></p>
            <div>
              <%= link_to image_tag(video.video_cover_image, alt:video.video_title), video.user %>
            </div>
            <div>
              <h3><%= video.video_title %></h3>
              <div class="video_content_item_ranking_meta">
                <i class="material-icons">favorite</i> <%= video.video_interaction_count %></p>
                <p><i class="material-icons">comment</i> <%= video.video_comment_count %></p>
                <p><i class="material-icons">share</i> <%= video.video_share_count %></p>
              </div>
              <div class="video_content_item_ranking_user">
                <%= link_to image_tag(video.user.user_covers, alt:video.user.user_nick_name), video.user %>
                <p><%= video.user.user_nick_name %></p>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </section>

  </div>
</article>

app/views/tags/search.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

  aaa
</body>
</html>

app/views/tags/show.html.erb
<% set_meta_tags title: "🎉「##{@tag.tag_title}」タグの人気動画をウェブで観よう！", description: "「##{@tag.tag_title}」タグの人気動画をウェブで観よう！ - TikTok（ティックトック）アプリがパソコンでも観れるようになりました！TikTok Webでは人気クリエイターや動画のランキングから人気タグの情報をお届けします！現在、開発中です。" %>

<div class="contents_wrap">

  <section class="video_content">
    <div class="video_player">
      <div class="canvas_heart_bubble">
        <div class="swiper-container">
          <div class="swiper-wrapper">
            <div class="swiper-slide">
              <%= video_tag "", muted: true, controls: true, id:"video", class:"video_0", playsinline: true, autoplay: true %>
            </div>
          </div>
          <div class="swiper-pagination"></div>
        </div>
      </div>
    </div>

    <% if @videos.present? %>
      <div class="video_content_meta">
        <h3 class="video_title"></h3>
        <div class="video_content_meta_tags">
          <p class="video_content_meta_tag"><a href=""></a></p>

        </div>
        <div class="video_content_meta_info">
          <p class="video_content_meta_info_play">
            <i class="material-icons">favorite</i> <span class="video_play_count"></span>
          </p>

          <p class="video_content_meta_info_comment">
            <i class="material-icons">comment</i> <span class="video_comment_count"></span>
          </p>
          <p class="video_content_meta_info_share">
            <i class="material-icons">share</i> <span class="video_share_count"></span>
          </p>
        </div>
      </div>

      <div class="video_content_profile">
        <div class="video_content_profile_image">
          <a class="video_user_covers" href=""><img src="" alt=""/></a>
        </div>
        <p class="video_user_nick_name"></p>
      </div>
    <% end %>

  </section>

  <article class="video_content_main">

    <section class="video_content_tag_info">
      <div class="video_content_tag_info_header">

        <%= image_tag('hash_tag.png', alt:"#") %>
        <h1>#<%= @tag.tag_title unless @tag.tag_title.nil? %></h1>
      </div>
      <div class="video_content_tag_info_meta">
        <p class="video_content_tag_info_meta_post">
          <%= @tag.tag_posts_count unless @tag.tag_posts_count.nil? %> <span>投稿</span>
        </p>

        <p class="video_content_tag_info_meta_view">
          <%= @tag.tag_views_count unless @tag.tag_views_count.nil? %> <span>回再生</span>
        </p>
      </div>
    </section>

    <section class="video_content_item">
      <h2><i class="material-icons">cake</i> 「<%= @tag.tag_title %>」おすすめ動画</h2>
      <ul>
        <% if @videos.present? %>

          <% @videos.shuffle.take(30).each_with_index do |video, i| %>
            <li>
              <%= image_tag video.video_cover_image, class: "video_data video_index_#{i}", alt: video.video_title,
                            data: {video_source: video.video_url,
                                   video_cover_image: video.video_cover_image,
                                   video_index: i,
                                   video_title: video.video_title,
                                   video_tags: video.video_tags,
                                   video_play_count: video.video_interaction_count,
                                   video_comment_count: video.video_comment_count,
                                   video_share_count: video.video_share_count,
                                   video_user_covers: video.user.user_covers,
                                   video_user_nick_name: video.user.user_nick_name,
                                   video_user_id: video.user.id,
                            } %>
            </li>
          <% end %>
        <% end %>
      </ul>
    </section>

    <div class="video_content_split_wrap">
      <div>
        <section class="video_content_item_ranking">
          <div class="video_content_item_ranking_header">
            <h2><i class="material-icons">cake</i> タグ動画ランキング(いいね数)</h2>
            <%= link_to "すべてのランキング", ranking_tag_path(@tag) %>
          </div>
          <ul>
            <% cache @videos_rank do %>
          <% @videos_rank.each_with_index do |video, index| %>
              <li>
                <p class="rank_index rank_index_<%= index + 1 %>"><%= index + 1 %></p>
                <div>
                  <%= link_to image_tag(video.video_cover_image, alt:video.video_title), video.user %>
                </div>
                <div>
                    <h3><%= video.video_title %></h3>
                    <div class="video_content_item_ranking_meta">
                      <p><i class="material-icons">favorite</i> <%= video.video_interaction_count %></p>
                      <p><i class="material-icons">comment</i> <%= video.video_share_count %></p>
                      <p><i class="material-icons">share</i> <%= video.video_comment_count %></p>
                    </div>
                    <div class="video_content_item_ranking_user">
                      <%= link_to image_tag(video.user.user_covers, alt:video.user.user_nick_name), video.user %>
                      <p><%= video.user.user_nick_name %></p>
                    </div>
                </div>
              </li>
            <% end %>
            <li class="ranking_more">
              <%= link_to "もっと見る", ranking_tag_path(@tag) %>
            </li>
            <% end %>

          </ul>
        </section>
      </div>

      <div>
        <section class="video_content_item_transition">
          <h2><i class="material-icons">cake</i> タグ総再生回数 推移</h2>
          <% cache @tag_histries_posts_trans_views_count do %>
            <%= line_chart @tag_histries_posts_trans_views_count , xtitle: "日付", ytitle: "総再生回数" %>
          <% end %>
        </section>

        <section class="video_content_item_transition">
          <h2><i class="material-icons">cake</i> タグ動画投稿数 推移</h2>
          <% cache @tag_histries_posts_trans_posts_count do %>
            <%= line_chart @tag_histries_posts_trans_posts_count , xtitle: "日付", ytitle: "動画投稿数" %>
          <% end %>
        </section>
      </div>
    </div>

    <section class="video_content_item_tags">
      <h2><i class="material-icons">cake</i> 関連するハッシュタグ</h2>
      <ul>
        <% if @videos.present? %>
          <% @recommend_tags.each do |tag| %>
            <li><%= link_to"##{tag}", search_tags_path(keyword: tag) %></li>
          <% end %>
        <% end %>
      </ul>
    </section>

  </article>

</div>

</body>
</html>